const API_URL = 'https://swapi.co/api/'
const PEOPLE_URL = 'people/:id'

const OPTS = { crossDomain: true }
const onPeopleResponse = function (persona) {
    console.log(`Hola yo soy, ${persona.name}`)
}

//NUESTRO CALLBACK ES onPeopleResponse
function obtenerPersonaje(id)
{
    const URL = `${API_URL}${PEOPLE_URL.replace(':id', id)}`
    $.get(URL, OPTS, onPeopleResponse)
}
/*
    IMPORTANNNNTEEE!!!!!!!!
    A CONTINUACION EJECUTAMOS LA FUNCION OBTENER PERSONAJE POR EL 1, 2 Y 3
    LA RESPUESTA DEBERÍA SER
    -LUKE SKYWALKER
    -R2-D2
    -C-3PO

    PERO CUANDO EJECUTAMOS EL CODIGO NO LOS IMPRIME DESORDENADO APESAR DE QUE
    COLOCAMOS QUE SE EJECUTE PRIMERO EL 1 LUEGO EL 2 Y POR ULTIMO EL 3

    ESTO ES LO QUE SE LLAMA EL ASINCRONISMO EN JAVASCRIPT EN SU MAXIMO EXPRESION

    BASICAMENTE NO SABEMOS EL ORDEN EN Q NOS LLEGA LA RESPUESTA

    EN POCAS PALABRAS HAY Q ENTENDER QUE LLAMAMOS MULTIPLES METODOS ASICRONICOS METODO ASINCRONICO PERO NO SABEMOS EN QUE ORDEN NOS LLEGA
    LA RESPUESTA, ESO DEPENDE DE NUESTRO SERVIDOR Y LO QUE SE TARDE EN LLAMAR CADA METODO ASINCRONICO

*/
obtenerPersonaje(1)//REQUEST NUMERO 1
obtenerPersonaje(2)//REQUEST NUMERO 2
obtenerPersonaje(3)//REQUEST NUMERO 3